[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "1.5.7"
solana-program = "1.18.26"
solana-client = "1.18.26"
solana-sdk = "1.18.26"
spl-associated-token-account = "1.1.1"
spl-token = "3.2.0"
